<?php

// TODO: language switcher. ✔

class User {
    // TODO: user login. ✔
    // TODO: user signup.
    // TODO: provider signup.
}
-----------------------------------

Class Category {
    // TODO: categories on header. ✔
    // TODO: add parent category on category details methods show page.
    // TODO: organize categories on dashboard >> parent >> children.
}
-----------------------------------

Class Resource {
    // TODO: add resource.
    // TODO: edit resource.
    // TODO: delete resource.
}
-----------------------------------

Class Feature {
    //
}
-----------------------------------

Class AcquiredFeature {
    //
}
-----------------------------------

Class Price {
    //
}
-----------------------------------

Class Availability {
    //
}
-----------------------------------

Class City {
    //
}
-----------------------------------

Class Unit {
    //
}
-----------------------------------
