<?php

// TODO: language switcher. ✔
// TODO: change footer to dark footer or make sidebar like theme switcher.
// TODO: 404 page

class User {
    // TODO: user login. ✔
    // TODO: user signup. ✔
    // TODO: user profile. ✔
    // TODO: provider signup.
    // TODO: user phone.
}
-----------------------------------

Class Category {
    // TODO: categories on header. ✔
    // TODO: add parent category on category details methods show page.
    // TODO: organize categories on dashboard >> parent >> children.
}
-----------------------------------

Class Resource {
    // TODO: resources.
    // TODO: add resource.
    // TODO: edit resource.
    // TODO: delete resource.
}
-----------------------------------

Class Feature {
    //
}
-----------------------------------

Class AcquiredFeature {
    //
}
-----------------------------------

Class Price {
    //
}
-----------------------------------

Class Availability {
    //
}
-----------------------------------

Class City {
    //
}
-----------------------------------

Class Unit {
    //
}
-----------------------------------
