<?php

// TODO: language switcher. ✔                                               10-2017
// TODO: 404 page.
// TODO: abandon hydrogen.
// TODO: change footer to dark footer or make sidebar like theme switcher.
// TODO: change $request from Collection ins back to Request in Controllers.
// TODO: fix styling in English.
// TODO: add placeholders to login/register/provider inputs.

// TODO: convert all inline styles to css sheets.
// TODO: use CDNs for all JS and CSS external files.
// TODO: remove JQuery migrate and upgrade functions to JQuery 3.
// TODO: update prices and availabilities by id to save ids from overflow.
// TODO: validate images sizes on production and constrain php.ini upload_max_filesize and memory_limit.
// TODO: make sure that revolution slider library fits for slow devices.
// TODO: move hydrogen config and hydrogen env variables to a config file.
// TODO: enhance Route::domain from Laravel docs (follow standards).

class User {
    // TODO: user login. ✔                                                  10-2017
    // TODO: user phone. ✔                                                  18-10-2017
    // TODO: user signup. ✔                                                 10-2017
    // TODO: user profile. ✔                                                10-2017
    // TODO: provider signup. ✔                                             18-10-2017
    // TODO: change name to fname and lname, and add gender to users.
    // TODO: email is not required.
}
-----------------------------------

class Category {
    // TODO: categories on header. ✔                                        10-2017
    // TODO: add parent category on category details methods show page.
    // TODO: organize categories on dashboard >> parent >> children.
}
-----------------------------------

class Resource {
    // TODO: resources. ✔                                                   10-2017
    // TODO: add resource. ✔                                                10-2017
    // TODO: edit resource. ✔                                               10-2017
    // TODO: availabilities. ✔                                              10-2017
    // TODO: multiple prices. ✔                                             10-2017
    // TODO: delete resource. ✔                                             10-2017
    // TODO: photos and cover. ✔                                            10-2017
    // TODO: resources listings. ✔                                          14-10-2017
    // TODO: resources show page. ✔                                         14-10-2017
    // TODO: featured resources dashboard. ✔                                15-10-2017
    // TODO: validate availabilities backend.
    // TODO: write custome arabic validation messages.
    // TODO: JQuery validate for resources/create and set availabilities.
    // TODO: add full functionality for dashboard resources, then update validation rules.
}
-----------------------------------

class Listings {
    // TODO: middleware to prevent search for parent categories.
    // TODO: listings list view from events-list-right-sidebar.html demo page.
    // TODO: paginate with JS to load more in the same page not to load with php.
}
-----------------------------------

class Feature {
    //
}
-----------------------------------

class AcquiredFeature {
    //
}
-----------------------------------

class Price {
    //
}
-----------------------------------

class Availability {
    //
}
-----------------------------------

class Country {
    // TODO: add arabic names.
}
-----------------------------------

class City {
    //
}
-----------------------------------

class Unit {
    //
}
-----------------------------------

class Photo {
    // TODO: optimize database columns.
}
-----------------------------------
